version: '2'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    command: --lower-case_table_names=1
    environment:
      MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
